# Generated by Django 2.2.13 on 2022-06-17 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.CharField(choices=[('01', 'Alta Verapaz'), ('02', 'Baja Berapaz'), ('03', 'Chimaltenango'), ('04', 'Chiquimula'), ('05', 'El Progreso'), ('06', 'Escuintla'), ('07', 'Guatemala'), ('08', 'Huehuetenango'), ('09', 'Izabal'), ('10', 'Jalapa'), ('11', 'Jutiapa'), ('12', 'Petén'), ('13', 'Quetzaltenango'), ('14', 'Quiché'), ('15', 'Retalhuleu'), ('16', 'Sacatepéquez'), ('17', 'San Marcos'), ('18', 'Santa Rosa'), ('19', 'Sololá'), ('20', 'Suchitepéquez'), ('21', 'Totonicapán'), ('22', 'Zacapa')], max_length=20, null=True)),
                ('tipo_empresa', models.IntegerField(choices=[(10, 'Plantas de extracción minera'), (20, 'Plantas de proceso de materia prima'), (30, 'Venta y alguier de maquinaria de contrucción'), (40, 'Transporte de materia prima'), (50, 'Transporte de productos para empresas extranjeras y nacionales'), (60, 'Servicios de contrucción en general')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=50)),
                ('precio_venta', models.FloatField(default=0)),
                ('materia_prima', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencias', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.Producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='api.Sucursal')),
            ],
        ),
    ]
