# Generated by Django 2.2.13 on 2022-06-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventario_producto_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Producto'), (2, 'Materia Prima')], default=1),
        ),
    ]
