# Generated by Django 2.2.13 on 2022-06-24 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220623_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('planta_extraccion', models.BooleanField(default=False)),
                ('planta_proceso', models.BooleanField(default=False)),
                ('venta_alquiler', models.BooleanField(default=False)),
                ('transporte_materia_prima', models.BooleanField(default=False)),
                ('transporte_productos', models.BooleanField(default=False)),
                ('servicios_construccion', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('cliente', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='api.Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='tipo_empresa',
            field=models.IntegerField(choices=[(10, 'Plantas de extracción minera'), (20, 'Plantas de proceso de materia prima'), (30, 'Venta y alquiler de maquinaria de contrucción'), (40, 'Transporte de materia prima'), (50, 'Transporte de productos para empresas extranjeras y nacionales'), (60, 'Servicios de contrucción en general')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='api.RolesModel'),
        ),
    ]
