# Generated by Django 2.2.13 on 2022-06-27 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_movimiento_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_destino', to='api.Sucursal'),
        ),
    ]
